name: Feature Branch Workflow

run-name: "Feature Branch CI -- ${{github.event.inputs.action}} Action - feature/${{github.event.inputs.feature_branch}} "

permissions:
  contents: 'write'
  id-token: 'write'

# Trigger workflow manually using the UI button
on:
  workflow_dispatch:
    inputs:
      action:
        type: string
        required: true
      feature_branch:
        type: string
        required: true
        
env:
  TRUNK_BRANCH: main
  FEATURE_BRANCH: feature/${{github.event.inputs.feature_branch}}
  PR_EXIST: 'false'
  PR_URL: ''
  PR_HTML_URL: ''

# Define jobs within the workflow
jobs:
  start:
    name: Check If PR Exist For Branch
    if: github.event.inputs.feature_branch != ''
    uses: BasedNoobDevelopers/maven-feature-branch-action/.github/workflows/feature-branch.yaml@main
    with:
        action: ${{inputs.action}}
        feature_branch: feature/${{github.event.inputs.feature_branch}}
    secrets:
      ACTION_TOKEN: "UYI"
